[[CURRENCIES]]
code="DOGE"
issuer="GBUMECTNBPLOFZS5QDB5SPA33372TMXMY7MZ7HQ6QRMWEGVZSJ3JUWPI"
name="DOGE Token"
desc="This is xusheng2 token created on Pi Testnet."
image="https://你的用户名.github.io/xusheng2.png"
